### ISSUE TITLE
Deleting module version does not remove files

### ISSUE THREAD

**Issue by pseudomorph** [MatthewJohn/terrareg#10]
when calling `delete_module_version` or `delete_module_provider`, which calls the former, archives and files associated with the module version are not removed from the system.

**Comment by MatthewJohn** [comment]
Thank you for raising this :) I'll happily create an upstream ticket - is there an urgency from your perspective on fixing this - or happy for it to be looked at within the next couple of weeks/month?

Thanks
Matt

**Comment by MatthewJohn** [comment]
Hey @pseudomorph ,

I raised an upstream ticket for this: https://gitlab.dockstudios.co.uk/pub/terrareg/-/issues/406

I've hopefully got an implementation for this sorted (pending test results!): https://gitlab.dockstudios.co.uk/pub/terrareg/-/merge_requests/340

Hopefully this looks okay - let me know if there's any issues :)

Many thanks
Matt

**Comment by MatthewJohn** [comment]
Hey @pseudomorph ,

I've now merged this and released in 2.71.3.
Hopefully this works as you'd hope - if not, feel free to re-open the issue :)

Thanks
Matt
