### ISSUE TITLE
Enforce authentication to be able to use Terrareg

### ISSUE THREAD

**Issue by MatthewJohn** [MatthewJohn/terrareg#16]
I've realised quite a few people are using OpenIDC and SAML within corporate environments.
There are a couple of tickets on the backlog (https://gitlab.dockstudios.co.uk/pub/terrareg/-/issues/392, https://gitlab.dockstudios.co.uk/pub/terrareg/-/issues/289) to enforce authentication (basically removing anonymous read access to Terrareg).
This would also mean adding authentication when using Terraform.

I'm creating this ticket as a place for people to vote on it, to see if it's something that would be useful - so please give it a thumbs up, if it's something that's wanted :)

Matt

**Comment by bmaximuml** [comment]
We're using terrareg with OIDC in a corporate environment in terraform. It would be very useful for us to be able to block all public access. Ideally, we'd have no public access, read access to any authenticated user, and write access to admins. Potentially an additional level of granularity to distinguish between write (can create / update modules) and admin (can admin users, can delete modules)

**Comment by MatthewJohn** [comment]
I've created a PR with these changes :) https://gitlab.dockstudios.co.uk/pub/terrareg/-/merge_requests

**Comment by MatthewJohn** [comment]
This has been released in v2.80.0 :)

**Comment by MatthewJohn** [comment]
Created gitlab issue: https://gitlab.dockstudios.co.uk/pub/terrareg/-/issues/503
gitlab-issue-id:503
