### ISSUE TITLE
Provide method to specify Terraform version per module

### ISSUE THREAD

**Issue by mrmattyboy1** [MatthewJohn/terrareg#20]
At the moment, each module needs a constraint, but ideally in the root module, each sub-module and each example.

Maybe a configuration on the module (or specified in the terrareg.json file) that determines the verison of Terraform that should be used for extraction could be useful?
Alternatively, could the entire code-base be scanned for any terraform version constraints and be used as a fallback?

**Comment by MatthewJohn** [comment]
This has been created: https://gitlab.dockstudios.co.uk/pub/terrareg/-/issues/443
