### ISSUE TITLE
dowload module fail

### ISSUE THREAD

**Issue by QloudXee** [MatthewJohn/terrareg#27]
Hi John 

I have a problem about download module file when run 'terraform init' ,the console shows that the url of module source.zip is invaild 
![image](https://github.com/MatthewJohn/terrareg/assets/32723965/c8736e6b-4c51-463e-bdf3-084857468a70)

however , I have found the source.zip in docker contianer 
![image](https://github.com/MatthewJohn/terrareg/assets/32723965/05bd268e-7680-441e-a087-963f1f03e8eb)

the docker logs shows this may be an 204 http error
![image](https://github.com/MatthewJohn/terrareg/assets/32723965/dc8d6935-09b6-42d8-bfb1-efcdba183793)

how should I fix it 
thanks a lot

**Comment by MatthewJohn** [comment]
Hey @QloudXee,

Thank you for raising this - it's very interesting - could you let me know which version of Terraform you're using at all?

I'll start testing to see if I can reproduce it

Many thanks
Matt

**Comment by QloudXee** [comment]
![image](https://github.com/MatthewJohn/terrareg/assets/32723965/fce6c44c-eae1-4e77-895c-84a31e15d2f0)
the version is 1.5.3

**Comment by MatthewJohn** [comment]
Ah, I think I have a suspicion! Would you be able to send across the "source" argument of the module call in your terraform?
Have you put a full URL, e.g. `https://example.com:5000/modules/my-tf-application__sbx/vnet1/azurerm/1.0.0` in there?
If so, this is just telling Terraform to use it as an HTTP source, as opposed to a registry.
If you change to:
```
module "test" {
  source  = "example.com:5000/my-tf-application__sbx/vnet1/azurerm"
  version = "1.0.0"
}
```
does it work any better? ;)

**Comment by QloudXee** [comment]
that is strange ,I have update url to "example.com:5000/modules/my-tf-application__sbx/vnet/azurerm" ,the terraform identify the "example.com" is scheme
![image](https://github.com/MatthewJohn/terrareg/assets/32723965/87ea9990-5dbd-49c0-9e18-2b98af8f212e)

**Comment by MatthewJohn** [comment]
Hey @QloudXee ,

No problem at all - glad it's working

I've fixed the issue you were having in this PR: https://gitlab.dockstudios.co.uk/pub/terrareg/-/merge_requests/373
I'll get it merged ASAP :)

Thanks
Matt

**Comment by MatthewJohn** [comment]
Created gitlab issue: https://gitlab.dockstudios.co.uk/pub/terrareg/-/issues/505
gitlab-issue-id:505
