### ISSUE TITLE
Feature Request: s3 as storage and serverless DB

### ISSUE THREAD

**Issue by Eli-Meitner** [MatthewJohn/terrareg#33]
Is there any way (or future plan) to use S3  as storage for modules/providers ? 
And any plans to support serveless DB suchas DynamoDB or DocumentDB ?
This is very important cost wise.

**Comment by Eli-Meitner** [comment]
Thank you for the quick response, I was sure I needed storage to store the modules (so I can fully migrate away from git), as for providers is there a plan to migrate them as well (right now from documentation it was not quite clear on how to add them to Terrareg)

**Comment by MatthewJohn** [comment]
Hey @Eli-Meitner 

Yep, that's correct, if you do not wish to use Git for the modules, then they will need to be stored. I expect the interaction with s3 _should be_ fairly simple to implement.

Out of interest, when you say about moving away from git, do you mean for the actual source code or just to serve Terraform from the registry without using git? (Not sure if you mean this scenario, but have created a ticket for being able to "index" from Git and serve the modules from local storage).

In terms of provider support, it is really not a production-ready function, so I wouldn't recommend using it (it was only really merged to main to avoid horrendous merge issues!). *But* providers work with a tight Github integration (following a similar approach to Hashicorp's registry) and the binaries are not stored by Terrareg (at least, this isn't an option at the moment) and Terraform downloads it straight from Github, so no storage is required on the Terrareg side (this _does_ mean that private providers are not yet supported, as well).

_Yeh_, I kind of realise the documentation for providers isn't very clear, and it's somewhere between not wanting to advertise this feature too much and also expecting that it might change a bit in the future, as the feature is improved :roll_eyes:

**Comment by Eli-Meitner** [comment]
Our main objective is to move to a private registry so we won't have to expose our modules (and their code) publicly, as for provider we are OK with it as we have only one  that we use for something very specific so we probably can move away from it. our objective is either moving the modules to private repo in bitbucket or keeping them in github but switching to private repo, once again thanks for the answer :-)

**Comment by Eli-Meitner** [comment]
Thanks

**Comment by MatthewJohn** [comment]
Hey @Eli-Meitner ,

Just to keep you updated - I've got a change prepared for adding S3 support: https://gitlab.dockstudios.co.uk/pub/terrareg/-/merge_requests/380

Just doing some final checks and trying to fix a CI configuration problem

Thanks
Matt

**Comment by MatthewJohn** [comment]
Hey @Eli-Meitner ,

The support for s3 was released in v3.1.0

Thanks
Matt

**Comment by MatthewJohn** [comment]
@Eli-Meitner 

Since S3 support has been added and the realistic possibility of supporting both SQL and Dynamodb/DocumentDB is going to be low, are you happy with this issue being closed?

Matt

**Comment by MatthewJohn** [comment]
Created gitlab issue: https://gitlab.dockstudios.co.uk/pub/terrareg/-/issues/507
gitlab-issue-id:507
