### ISSUE TITLE
Bug: Namespaces incorrectly showing as empty

### ISSUE THREAD

**Issue by bmaximuml** [MatthewJohn/terrareg#39]
I have some modules defined in a namespace where both the namespace and the modules are defined using the [terraform provider](https://github.com/DockStudios/terraform-provider-terrareg/blob/main/internal/provider/git_provider_data_source.go). This namespace is hidden in the list of namespaces in the gui, and only shows up when I click on the `Show empty namespaces` button. Clicking on the namespace does then show a list of modules.

**Comment by MatthewJohn** [comment]
Hey @bmaximuml ,

As far as I know, this _should_ happen until the provider has a version indexed, at which point, the module will be available in search results (though wasn't 100% aware it hid it from main namespace list).
If you index a version of the module, does it work as expected afterwards?

Matt

**Comment by MatthewJohn** [comment]
Created gitlab issue: https://gitlab.dockstudios.co.uk/pub/terrareg/-/issues/510
gitlab-issue-id:510
