### ISSUE TITLE
Provide alternative module constraints for pre-1.0.0 releases

### ISSUE THREAD

**Issue by mrmattyboy1** [MatthewJohn/terrareg#49]
Since semantic versioning has different requirements for pre-1.0.0 releases, meaning that breaking changes can be introduced, it would be beneficial to be able to use a different constraint for these versions (e.g. to pin to minor or even a particular version)

**Comment by MatthewJohn** [comment]
Created gitlab issue: https://gitlab.dockstudios.co.uk/pub/terrareg/-/issues/525
gitlab-issue-id:525

**Comment by mrmattyboy1** [comment]
Release in v3.9.0
