### ISSUE TITLE
Terraform compatibility is not shown for version constraints that just contain a version

### ISSUE THREAD

**Issue by mrmattyboy1** [MatthewJohn/terrareg#52]
e.g.
```
terraform {
  required_versions = "1.5.0"
}
```

**Comment by MatthewJohn** [comment]
Created gitlab issue: https://gitlab.dockstudios.co.uk/pub/terrareg/-/issues/530
gitlab-issue-id:530

**Comment by MatthewJohn** [comment]
Addressed in https://gitlab.dockstudios.co.uk/pub/terrareg/-/merge_requests/409

**Comment by MatthewJohn** [comment]
Fixed in https://github.com/MatthewJohn/terrareg/releases/tag/v3.7.1
