### ISSUE TITLE
Completely disable analytics?

### ISSUE THREAD

**Issue by mdeeks** [MatthewJohn/terrareg#6]
Is there a way to completely disable analytics? We don't want to use it at all since the extra field in the Usage Builder is confusing as is the custom url it generates. We already have issues with people copy/pasting terraform from other teams and this will only lead to incorrect analytics and users confused by URLs.

**Comment by MatthewJohn** [comment]
HI Mike,

I'm afraid the only functionality that currently goes towards supporting that is: https://github.com/MatthewJohn/terrareg/blob/main/docs/CONFIG.md#allow_unidentified_downloads, which will allow the calls to the module to exclude an analytics token.
However, the usage example usage, usage builder and rewritten terraform in README/examples will still contain a placeholder.

I have created https://gitlab.dockstudios.co.uk/pub/terrareg/-/issues/372, which we can implement a toggle for disable analytics in those remaining places - I'll try to take a look this weekend

Many thanks
Matt

**Comment by MatthewJohn** [comment]
Hi Mike,

I've made some changes to add a configuration to completely disable analytics: https://gitlab.dockstudios.co.uk/pub/terrareg/-/merge_requests/320
Will hopefully get this merged soon :)

Many thanks
MAtt

**Comment by mdeeks** [comment]
Thanks! I'll give it a shot

**Comment by MatthewJohn** [comment]
This is now released, so should be available from main or 2.66.0
Let me know how it looks :)

**Comment by mdeeks** [comment]
lgtm, thanks!
