### ISSUE TITLE
Display application version number

### ISSUE THREAD

**Issue by alexusarov** [MatthewJohn/terrareg#61]
It would be helpful to display the application version number in the GUI, preferably on the right side of the toolbar.

**Comment by MatthewJohn** [comment]
Created gitlab issue: https://gitlab.dockstudios.co.uk/pub/terrareg/-/issues/539
gitlab-issue-id:539

**Comment by MatthewJohn** [comment]
This has been added in https://gitlab.dockstudios.co.uk/pub/terrareg/-/merge_requests/414
It will be released within the next hour :)

Many thanks
Matt
