### ISSUE TITLE
Update terraform docs to new version

### ISSUE THREAD

**Issue by mark-jones-rga** [MatthewJohn/terrareg#63]
It looks like terraform docs is finally being maintained again.   Suggesting updating the Dockerfile to use the newer version for updated security vulnerabilities. https://github.com/terraform-docs/terraform-docs/releases/tag/v0.19.0

**Comment by MatthewJohn** [comment]
Created gitlab issue: https://gitlab.dockstudios.co.uk/pub/terrareg/-/issues/544
gitlab-issue-id:544

**Comment by MatthewJohn** [comment]
Merged in https://gitlab.dockstudios.co.uk/pub/terrareg/-/merge_requests/417 :)

Thanks @mark-jones-rga

**Comment by mark-jones-rga** [comment]
Thank brosef!  We are going to be re-deploying back with upstream here soon.  We diverged big time a while back for security vulnerabilities, but I think most are resolved now!

**Comment by MatthewJohn** [comment]
Though I noticed that the release bot didn't care about the commit message, so it’s merged but not tagged or built - will fix this tomorrow.
Also, I’m rolling out a dependency fixing tool (rather than dependabot ), so will get some package updates done as well soon :)

Matt
