### ISSUE TITLE
Failed to download module

### ISSUE THREAD

**Issue by sebastiencaty** [MatthewJohn/terrareg#64]
I've configured terrareg (v3.12) to force auth on all users and download. I have configured to following var :

```
PUBLIC_URL=https://internal.domain
DOMAIN_NAME=internal.domain
ADMIN_AUTHENTICATION_TOKEN=secret
ALLOW_UNAUTHENTICATED_ACCESS=False
TERRAFORM_PRESIGNED_URL_SECRET=secret
TERRAFORM_OIDC_IDP_SUBJECT_ID_HASH_SALT=secret
TERRAFORM_OIDC_IDP_SIGNING_KEY_PATH=/path/to/key.pem
DISABLE_ANALYTICS=True
ALLOW_MODULE_HOSTING=Enforce
DEFAULT_TERRAFORM_VERSION=1.9.5
```

Got a few modules uploaded (using S3 for storage).

I can run the following command successfully : `terraform login internal.domain`. Browser pops up, I can login using the value from `ADMIN_AUTHENTICATION_TOKEN` and terraform sets the auth token properly in `~/.terraform.d/credentials.tfrc.json`

However when running `terraform init` I get the following error message :
```
Error: Failed to download module
Could not download module "module" from https://internal.domain/v1/terrareg/modules/namespace/module/provider/version/source.zip//modules/module?presign=xxxxxxxxxxxxxxxxxxxx: bad response code: 403.
```

Without auth terraform init works fine but I wanted to required some auth quickly before going for OIDC.

Should this work? Am I missing some conf?

**Comment by MatthewJohn** [comment]
Hey Sebastien,

Sorry that you’re experiencing these issues.
I would recommend enabling debug and then going to the url in the browser to see the error that you get from the 403 (I believe terraform should show you the body - are you using an old version of terraform (pre-1?) as I believe this didn’t Show the response body)

Matt

**Comment by sebastiencaty** [comment]
This `DEFAULT_TERRAFORM_VERSION=1.9.5` should set terraform to version 1.9.5?

Interresting, following the URL, I get a 404.

`https://internal.domain/v1/terrareg/modules/namespace/module/provider/version/source.zip//modules/module?presign=xxxxxxxxxxxxxxxxxxxx`

But this works (get a presign key error)

`https://internal.domain/v1/terrareg/modules/namespace/module/provider/version/source.zip?presign=xxxxxxxxxxxxxxxxxxxx`

If I set `ALLOW_UNAUTHENTICATED_ACCESS=False`, then terraform init downloads the module and terraform plan works as expected.

URL not generated correctly?

I have used the terraform provider to create all the namespaces and modules.
git_path is defined as : /modules/{module}
git_tag_format : {version}

From the web interface everything looks good. I can see all namespaces/modules/version releases. Source code URL goes right to the module source, usage example looks good and works for unauthenticated access.

**Comment by MatthewJohn** [comment]
I’m afraid I’m travelling atm. But yes, that url is wrong.
I think it was broken in a recent release so for now I think downgrading to URL not generated correctly
For now I think downgrading to v3.7.1 should fix your issue, im afraid
I’ll take a look at fixing tomorrow - apologies!
Matt

**Comment by MatthewJohn** [comment]
For info, the generated url, I suspect, should be

…./download?signingkey=abcsnne//path/to/module
As a result of the signing key being on the end, terraform is not treating the module path as such and is just passing it to the request to terrareg

**Comment by sebastiencaty** [comment]
Rolling back is a bit of a pain since the current database isn't backwards compatible to 3.7.1

I'll wait for when you get a chance to fix this. Happy to help debug and test.

**Comment by MatthewJohn** [comment]
Hey @sebastiencaty,

I've pushed a fix that I think should work - struggling to find time to completely verify: https://github.com/MatthewJohn/terrareg/pull/new/invalid-signed-url-when-module-uses-subpath

I'll take another look later today :)

Many thanks
Matt

**Comment by sebastiencaty** [comment]
Great! I'll try this today and report back.

**Comment by sebastiencaty** [comment]
hmmmm getting closer

```
Could not download module source code from
│ "https://internal.domain/v1/terrareg/modules/namespace/module/aws/1.3.0/source.zip?presign=xxxxxxx//modules/module":
│ bad response code: 403.
```

Opening the url in a browser gives this :

```
{"message": "Invalid pre-signed URL key"}
```

Configuration issue? Is there something that should be defined for the terraform client? `TERRAFORM_PRESIGNED_URL_SECRET` is set with a random value.

**Comment by MatthewJohn** [comment]
It's intereseting - I wonder if terraform itself doens't support a redirect URL for the module source that contains the path.
I will try to look into the OpenTofu source to see if this is the case

**Comment by MatthewJohn** [comment]
There might well be a work-around in the mean time - if you enable the "archive git path" and re-index the module, does it fix the issue?

**Comment by sebastiencaty** [comment]
I'm already pushing a zip file that I make from a github action using the header for auth on terrareg api. This zip file contains only a single module. I found it easier to push to terrareg rather than pull. I have also configured terrareg to use only s3 storage.

Inside the archive I do have the proper path in the format of `modules/module/tf-files`.

Using terrerag terraform provider, the module has a git path defined as the same structure `modules/module`.

Upload works and I can see the namespace with the module and all versions that I have pushed. Terraform init works for downloading the modules without auth. With auth is when I have this issue. 

I have tried (with the generated url from the patched version) to download the module and removing the module path at the end. This actually works! It also match the source url for the module suggested by terrareg (internal.domain/namespace/module/provider)

My following issue would be providing the registry credentials in a automated way since the token does expire. Works fine in interactive mode but not for automated deployment. Do you plan to allow for some permanent token? Or is this more a matter of using oidc?

**Comment by MatthewJohn** [comment]
> Do you plan to allow for some permanent token? Or is this more a matter of using oidc?
You could either use OIDC on the agent or use a token from the analytics auth keys (https://matthewjohn.github.io/terrareg/CONFIG/#allow_unidentified_downloads), which should provide authentication :)

**Comment by MatthewJohn** [comment]
Created gitlab issue: https://gitlab.dockstudios.co.uk/pub/terrareg/-/issues/547
gitlab-issue-id:547

**Comment by sebastiencaty** [comment]
Using analytics auth keys did the trick. Nice option to use before getting oidc up and running properly.

I removed the path from the generated url and everything works. I'm not sure if it's suposed to ever be present there. Even when using submodules, the full path is expected to be in the downloaded archive but the source.zip seems to be at the "root" level.

Since I have several modules inside the same git repository, I have named the namespace to be the repo name. Then I have defined several modules with git_path defined since all those modules are inside their own sub-directory inside a directory named `modules` from the root.

The provided terraform usage exemple is generated correctly and I simply copy/pasted it in my terraform code. The generated url for the source code in github also points at the proper place, right in the module code for the defined tag version.

Without defining git_path, the generated source code url ends up being incorrect.

Am I using git_path incorrectly? Unexpected usage?

**Comment by MatthewJohn** [comment]
> Using analytics auth keys did the trick. Nice option to use before getting oidc up and running properly.
Great :)

> I removed the path from the generated url and everything works. I'm not sure if it's suposed to ever be present there. Even when using submodules, the full path is expected to be in the downloaded archive but the source.zip seems to be at the "root" level.

For archives, there's two ways it can work:
 * It can create the zip file at the root of the repository (by default)
 * Create it using the git_path (by enabling the archive_git_path option) (note that you'd need to re-index the modules if you change this option)

if the archive is captured at the root level, the UI doesn't display url sub-path in the example URLs - when the module is requested, the returned redirect URL contains this git path (the theory that Terraform will download the zip and use the sub-directory from the extracted zip). This same functionality is done with git modules - so there is no path in the initial URL, but the redirect provides a URL with the path included - and this works. I'm assuming this is an issue with how Terraform handles archive URLs and can't handle redirect URLs that contain the sub path.

I assume that the URL that you have in the UI doens't contain the sub-path, correct?

For now, I would try enabling the archive_git_path to see if it does solve your use-case for now, if you can.

If I'm right in saying that Terraform doesn't support this sub-path for archives in the redirect URL, then I might need to change to provide the sub-path within the URL displayed within the UI instead, which would be unfortunate

**Comment by sebastiencaty** [comment]
> I assume that the URL that you have in the UI doens't contain the sub-path, correct?
Correct.

>For now, I would try enabling the archive_git_path to see if it does solve your use-case for now, if you can.
Did not see that, found it in the API docs but not with the terraform provider. Looking at the code, it's not hooked up yet. I'll see what I can do with this next week.

**Comment by MatthewJohn** [comment]
Hey @sebastiencaty ,

I took a bit of a guess and tested using an ampersand seperator after the signing key and it appears to have worked!
I've pushed the latest changes to the branch :) 
I'll work on some tests and try to get it released today/tomorrow.

Many thanks
Matt

**Comment by sebastiencaty** [comment]
Hi John,

Tried the new update. It does download but then I noticed that terraform will unpack the archive with the sub-path included. So running terraform ends up not working due to the module not being present at the path defined in the module source.

I've added the sub-path `//modules/module-name` to the source and then it all works.

I don't mind having to add this, but shouldn't the UI usage also show the sub-path in this case?

**Comment by sebastiencaty** [comment]
Sorry hit the wrong button.

**Comment by MatthewJohn** [comment]
The only workaround I have so far as it to inject the presign key into the URL path in the redirect, meaning it becomes something like:
```
/v1/terrareg/modules/adgADG2/example-submodule/null/1.1.0/source.zip/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHBpcnkiOiIyMDI0LTExLTA1VDA3OjQyOjE4LjkxNTU4OSIsInVybCI6Ii92MS90ZXJyYXJlZy9tb2R1bGVzL2FkZ0FERzIvZXhhbXBsZS1zdWJtb2R1bGUvbnVsbC8xLjEuMC9zb3VyY2UuemlwIn0.BQO-XVDoJYmAwhOodS04Nl4J7sRtZTwxdiFMpXrO32Y//some/submodule
```

I don't _really_ want to do this as I'd like to consider the possible security implications of this (at least from a logging perspective). But also, I'm seeing some other issues with testing this, so trying to get it working.

Matt

**Comment by MatthewJohn** [comment]
Hey,

I've managed to get the download working, moving the presign key to the path. I've updated the branch, if you did want to test it.
But I'm going to do a little more reading to determine if it's a safe solutions

Many thanks
Matt

**Comment by sebastiencaty** [comment]
Hi Matt,

I've been testing your latest commit to this test branch and everything works well. Have you been to determine if this is safe?

**Comment by MatthewJohn** [comment]
Hey @sebastiencaty ,

That's great thank for you confirming. I'll working on some tests and limiting how frequently it's used

Many thanks
Matt

**Comment by MatthewJohn** [comment]
Hey @sebastiencaty,

This is now merged and will release itself in the next hour

Many thanks
Matt
