### ISSUE TITLE
Character '@' in git tag is incorrectly parsed

### ISSUE THREAD

**Issue by rafaesin** [MatthewJohn/terrareg#67]
Hello

I'm setting terrareg as a private registry migrating from github with `release-please`. [Release-please](https://github.com/googleapis/release-please) is an automation that automatically create tags and releases in the repository following some rules. I'll not get into it extensively but the gist of it is that we keep several different modules in one single repository and every modification in a particular module that is merged creates a new tag for the repo with the format "module-name@v1.2.3"

When trying to create a module using the interface, I noticed that if I use the pattern `module-name@v{version}`, the `@` gets incorrectly parsed and the resulting saved configuration is `module-name%40v{version}`.

I've located the part of the code that parses this field on `models.py` in the `update_git_tag_format` function.
```sanitised_git_tag_format = urllib.parse.quote(git_tag_format, safe=r'/{}')```

Is it possible to add `@` as a safe character in this parse?

**Comment by MatthewJohn** [comment]
Created gitlab issue: https://gitlab.dockstudios.co.uk/pub/terrareg/-/issues/549
gitlab-issue-id:549

**Comment by MatthewJohn** [comment]
Thanks @rafaesin for this - I'll try to merge as soon as I can

**Comment by MatthewJohn** [comment]
This has been released in https://github.com/MatthewJohn/terrareg/releases/tag/v3.12.1
