### ISSUE TITLE
OIDC Redirect URI

### ISSUE THREAD

**Issue by vishnukv-facets** [MatthewJohn/terrareg#69]
Hi, i want to use google oauth , but i cant seem to find the redirect URI path for terrareg
can someone help here?
went through the docs, was unable to find it

**Comment by MatthewJohn** [comment]
Created gitlab issue: https://gitlab.dockstudios.co.uk/pub/terrareg/-/issues/550
gitlab-issue-id:550

**Comment by MatthewJohn** [comment]
Hey @vishnukv-facets,

The details for the OIDC URLs can be found here: https://matthewjohn.github.io/terrareg/security/#openid-connect
So for the redirect URL, it's: https://<terrareg-instance-domain>/openid/callback

Hope this helps

Matt
